# Generated by Django 5.0.6 on 2024-06-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_tag_articles_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-scopes__is_main'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
