# Generated by Django 5.0.6 on 2024-06-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag__name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
